EMBEDDING_MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_MODEL_MAX_INPUT_LENGTH = 384
EMBEDDING_MODEL_DEVICE = "cpu"

VECTOR_DB_OUTPUT_COLLECTION_NAME = "tech-news"

START_DATE = "2024-12-01"
TOP_NEWS_LIMIT = 5
NEWS_QUERY = "ai"
