peft_model:
  id: jdpsc/fine-tuned-falcon-7b-lora:1.0.0
model:
  id: tiiuae/falcon-7b-instruct
  template_name: "falcon"
  max_new_tokens: 512
  temperature: 1.0
setup:
  device: cuda:0
  debug: False
dataset:
  file: "testing_dataset.json"
